sequenceDiagram
  participant me as User
  participant app as Call Me Maybe
  participant twilio as Twilio
  participant office as Unemployment Office

  me ->>app: Start App
  loop every x seconds
    app->>twilio: start conference call
    twilio->>office: call the office
    alt line busy
      app->>app: sleep
    else call me
      twilio->>me: dial me in
    end
  end
